name: Auto Changelog & Release

on:
  push:
    branches:
      - main
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: https://git.0xmax42.io/actions/auto-changelog-release-action@main
